"""
Review Forge — turn the research graph into literature-review deliverables.

One call produces a "review pack":

    review.bib            BibTeX for every included paper
    review.ris            RIS (EndNote / Zotero / Mendeley import)
    synthesis_matrix.csv  paper x attribute matrix (theme, rating, methods...)
    review_scaffold.md    themed review skeleton with citation keys
    prisma_flow.md        PRISMA-2020 flow counts from the audit trail

Everything exported is either bibliographic fact (citations are not
copyrightable), the user's own ratings/decisions, or NEW text synthesised
by the local LLM from titles and metadata. Third-party abstracts and full
texts are never copied into the exports — papers are referenced via DOI.
"""

from __future__ import annotations

import csv
import logging
import re
import time
from pathlib import Path
from typing import Optional

from researchbuddy.config import (
    REVIEW_EXPORT_DIR, REVIEW_MIN_RATING_INCLUDE, LLM_ENABLED,
    LLM_TEMPERATURE_LOW,
)
from researchbuddy.core.graph_model import HierarchicalResearchGraph, PaperMeta
from researchbuddy.core import audit

logger = logging.getLogger(__name__)


# ── Citation keys ─────────────────────────────────────────────────────────────

_STOPWORDS = {"a", "an", "the", "of", "in", "on", "and", "or", "for", "to",
              "with", "from", "into", "via", "by"}


def bibtex_key(meta: PaperMeta) -> str:
    """FirstauthorYearFirstword, e.g. smith2021drift."""
    if meta.authors:
        last = meta.authors[0].split()[-1]
    else:
        last = "anon"
    last = re.sub(r"[^A-Za-z]", "", last).lower() or "anon"
    year = str(meta.year) if meta.year else "nd"
    word = ""
    for w in re.findall(r"[A-Za-z]+", meta.title or ""):
        if w.lower() not in _STOPWORDS:
            word = w.lower()
            break
    return f"{last}{year}{word}"


def assign_keys(papers: list[PaperMeta]) -> dict[str, str]:
    """paper_id -> unique citation key (duplicates get b, c, ... suffixes)."""
    keys: dict[str, str] = {}
    used: dict[str, int] = {}
    for m in sorted(papers, key=lambda p: (p.year or 0, p.title)):
        base = bibtex_key(m)
        n = used.get(base, 0)
        keys[m.paper_id] = base if n == 0 else f"{base}{chr(ord('a') + n)}"
        used[base] = n + 1
    return keys


# ── Paper selection ───────────────────────────────────────────────────────────

def review_papers(graph: HierarchicalResearchGraph,
                  include_unrated: bool = True) -> list[PaperMeta]:
    """
    Papers that belong in the review: everything rated at/above the include
    threshold, plus seed PDFs (implicitly relevant), optionally plus unrated
    graph papers (background corpus). User thoughts are never exported.
    """
    out = []
    for m in graph.all_papers():
        if m.kind != "paper":
            continue
        if m.user_rating is not None:
            if m.user_rating >= REVIEW_MIN_RATING_INCLUDE:
                out.append(m)
        elif m.source == "seed" or include_unrated:
            out.append(m)
    out.sort(key=lambda p: (p.year or 0, p.title))
    return out


# ── BibTeX ────────────────────────────────────────────────────────────────────

def _bib_escape(s: str) -> str:
    return (s or "").replace("\\", "").replace("{", "(").replace("}", ")") \
                    .replace("&", r"\&").replace("%", r"\%").strip()


def _entry_type(meta: PaperMeta) -> str:
    v = (meta.venue or "").lower()
    if not meta.venue:
        return "misc"
    if any(k in v for k in ("proceedings", "conference", "workshop", "symposium")):
        return "inproceedings"
    return "article"


def export_bibtex(graph: HierarchicalResearchGraph, path: Path,
                  papers: Optional[list[PaperMeta]] = None) -> int:
    papers = papers if papers is not None else review_papers(graph)
    keys = assign_keys(papers)
    lines: list[str] = [
        "% Generated by ResearchBuddy Review Forge",
        f"% {time.strftime('%Y-%m-%d %H:%M')}  ({len(papers)} entries)",
        "",
    ]
    for m in papers:
        etype = _entry_type(m)
        fields = [("title", _bib_escape(m.title))]
        if m.authors:
            fields.append(("author", " and ".join(_bib_escape(a) for a in m.authors)))
        if m.year:
            fields.append(("year", str(m.year)))
        if m.venue:
            venue_field = "booktitle" if etype == "inproceedings" else "journal"
            fields.append((venue_field, _bib_escape(m.venue)))
        if m.doi:
            fields.append(("doi", m.doi))
        if m.url:
            fields.append(("url", m.url))
        body = ",\n".join(f"  {k:<10} = {{{v}}}" for k, v in fields)
        lines.append(f"@{etype}{{{keys[m.paper_id]},\n{body}\n}}\n")
    Path(path).write_text("\n".join(lines), encoding="utf-8")
    return len(papers)


# ── RIS ───────────────────────────────────────────────────────────────────────

def export_ris(graph: HierarchicalResearchGraph, path: Path,
               papers: Optional[list[PaperMeta]] = None) -> int:
    papers = papers if papers is not None else review_papers(graph)
    out: list[str] = []
    for m in papers:
        ty = "CONF" if _entry_type(m) == "inproceedings" else \
             ("JOUR" if m.venue else "GEN")
        out.append(f"TY  - {ty}")
        out.append(f"TI  - {m.title}")
        for a in m.authors:
            out.append(f"AU  - {a}")
        if m.year:
            out.append(f"PY  - {m.year}")
        if m.venue:
            out.append(f"JO  - {m.venue}")
        if m.doi:
            out.append(f"DO  - {m.doi}")
        if m.url:
            out.append(f"UR  - {m.url}")
        out.append("ER  - ")
        out.append("")
    Path(path).write_text("\n".join(out), encoding="utf-8")
    return len(papers)


# ── Themes (level-1 clusters) ─────────────────────────────────────────────────

def _theme_label(graph: HierarchicalResearchGraph,
                 paper_ids: list[str], max_words: int = 4) -> str:
    """Label a cluster from its member titles (KeyBERT, word-count fallback)."""
    titles = [graph.get_paper(p).title for p in paper_ids if graph.get_paper(p)]
    combined = ". ".join(titles)
    try:
        from researchbuddy.core.graph_model import _get_cached_keybert
        kb = _get_cached_keybert()
        if kb is not None:
            kws = kb.extract_keywords(
                combined, keyphrase_ngram_range=(1, 3),
                stop_words="english", top_n=1,
            )
            if kws:
                return kws[0][0].title()
    except Exception:
        pass
    # Fallback: most common non-stopword title words
    counts: dict[str, int] = {}
    for t in titles:
        for w in re.findall(r"[A-Za-z]{4,}", t.lower()):
            if w not in _STOPWORDS:
                counts[w] = counts.get(w, 0) + 1
    top = sorted(counts, key=counts.get, reverse=True)[:max_words]
    return " ".join(w.title() for w in top) or "Untitled Theme"


def themes(graph: HierarchicalResearchGraph,
           papers: Optional[list[PaperMeta]] = None) -> list[dict]:
    """
    Group review papers by their level-1 (niche) cluster.
    Papers outside any niche land in an 'Unclustered' bucket.
    """
    papers = papers if papers is not None else review_papers(graph)
    by_id = {m.paper_id: m for m in papers}
    p2n = graph.paper_to_niche()

    groups: dict[str, list[PaperMeta]] = {}
    for pid, m in by_id.items():
        groups.setdefault(p2n.get(pid, "unclustered"), []).append(m)

    out = []
    for nid, members in sorted(groups.items(),
                               key=lambda kv: -len(kv[1])):
        members.sort(key=lambda m: (m.year or 0, m.title))
        label = ("Unclustered" if nid == "unclustered"
                 else _theme_label(graph, [m.paper_id for m in members]))
        years = [m.year for m in members if m.year]
        out.append({
            "cluster_id": nid,
            "label":      label,
            "papers":     members,
            "n_rated":    sum(1 for m in members if m.user_rating is not None),
            "year_range": (min(years), max(years)) if years else None,
        })
    return out


# ── Synthesis matrix ──────────────────────────────────────────────────────────

def export_synthesis_matrix(graph: HierarchicalResearchGraph, path: Path,
                            papers: Optional[list[PaperMeta]] = None) -> int:
    papers = papers if papers is not None else review_papers(graph)
    keys = assign_keys(papers)
    theme_of = {}
    for th in themes(graph, papers):
        for m in th["papers"]:
            theme_of[m.paper_id] = th["label"]

    cols = ["cite_key", "title", "authors", "year", "venue", "doi",
            "peer_reviewed", "rating", "decision", "theme",
            "has_fulltext", "n_sections", "n_refs", "source"]
    with open(path, "w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(cols)
        for m in papers:
            w.writerow([
                keys[m.paper_id],
                m.title,
                "; ".join(m.authors),
                m.year or "",
                m.venue,
                m.doi,
                {True: "yes", False: "no"}.get(m.is_peer_reviewed, ""),
                f"{m.user_rating:.0f}" if m.user_rating is not None else "",
                audit.screen_decision(m.user_rating) if m.user_rating is not None else "",
                theme_of.get(m.paper_id, ""),
                "yes" if m.filepath else "no",
                len(m.section_index),
                len(m.local_refs),
                m.source,
            ])
    return len(papers)


# ── LLM theme synthesis (optional, fully original text) ──────────────────────

def _llm_theme_synthesis(theme: dict, keys: dict[str, str]) -> Optional[str]:
    """Ask the local LLM for an original mini-synthesis of one theme."""
    if not LLM_ENABLED:
        return None
    try:
        from researchbuddy.core.llm import get_llm
        client = get_llm()
        if not client.is_available():
            return None
    except Exception:
        return None

    items = []
    for m in theme["papers"][:12]:
        rating = f", user-rated {m.user_rating:.0f}/10" if m.user_rating else ""
        items.append(f"- [{keys[m.paper_id]}] {m.title} "
                     f"({m.year or 'n.d.'}{rating})")
    prompt = (
        "You are helping draft a literature review. Below are papers in one "
        f"research theme ('{theme['label']}'). Write 3-4 original sentences "
        "synthesising what this body of work covers and how it developed over "
        "time. Cite papers inline using their bracketed keys. Do NOT quote or "
        "reproduce any text from the papers; write entirely in your own words.\n\n"
        + "\n".join(items)
    )
    return client.generate(prompt, temperature=LLM_TEMPERATURE_LOW,
                           max_tokens=220)


# ── Review scaffold (Markdown) ────────────────────────────────────────────────

def export_review_scaffold(graph: HierarchicalResearchGraph, path: Path,
                           papers: Optional[list[PaperMeta]] = None,
                           use_llm: bool = True) -> Path:
    papers = papers if papers is not None else review_papers(graph)
    keys = assign_keys(papers)
    ths = themes(graph, papers)
    counts = audit.prisma_counts()

    L: list[str] = []
    L.append("# Literature Review Scaffold")
    L.append("")
    L.append(f"*Generated by ResearchBuddy on {time.strftime('%Y-%m-%d')} — "
             f"{len(papers)} papers across {len(ths)} themes.*")
    L.append("")
    L.append("> Citation keys match `review.bib` / `review.ris` in this pack. "
             "Papers are referenced by DOI; no third-party text is reproduced "
             "here. Synthesis paragraphs (when present) were generated locally "
             "and must be verified against the sources before use.")
    L.append("")

    if counts["n_searches"] or counts["screened"]:
        L.append("## Search record (auto-generated)")
        L.append("")
        L.append(f"- Database searches run: **{counts['n_searches']}** "
                 f"({counts['identified_search']} records identified)")
        if counts["identified_snowball"]:
            L.append(f"- Citation snowballing: **{counts['identified_snowball']}** "
                     "additional records")
        L.append(f"- Screened: **{counts['screened']}** — "
                 f"included {counts['included']}, excluded {counts['excluded']}")
        L.append(f"- Full texts retrieved (legal OA): "
                 f"**{counts['fulltext_retrieved']}**")
        L.append("")

    for i, th in enumerate(ths, 1):
        yr = (f", {th['year_range'][0]}–{th['year_range'][1]}"
              if th["year_range"] else "")
        L.append(f"## Theme {i}: {th['label']} "
                 f"({len(th['papers'])} papers{yr})")
        L.append("")

        synthesis = _llm_theme_synthesis(th, keys) if use_llm else None
        if synthesis:
            L.append(synthesis.strip())
        else:
            L.append("*[Write 3-5 sentences synthesising this theme: what "
                     "question it addresses, how methods evolved, where "
                     "findings agree or conflict.]*")
        L.append("")
        L.append("| Cite | Year | Rating | Title | DOI |")
        L.append("|---|---|---|---|---|")
        for m in th["papers"]:
            rating = f"{m.user_rating:.0f}" if m.user_rating is not None else "—"
            doi = f"[{m.doi}](https://doi.org/{m.doi})" if m.doi else "—"
            L.append(f"| `{keys[m.paper_id]}` | {m.year or '—'} | {rating} "
                     f"| {m.title[:90]} | {doi} |")
        L.append("")

    # ── Gaps & next steps ───────────────────────────────────────────────────
    under = [th for th in ths if len(th["papers"]) >= 3
             and th["n_rated"] < max(2, len(th["papers"]) // 3)]
    L.append("## Coverage gaps & next steps")
    L.append("")
    if under:
        for th in under:
            L.append(f"- **{th['label']}** — only {th['n_rated']} of "
                     f"{len(th['papers'])} papers screened; review this theme "
                     "or run a snowball round from it.")
    else:
        L.append("- No under-screened themes detected. Consider a forward "
                 "snowball round on your most recent includes to catch "
                 "brand-new citing work.")
    L.append("")
    L.append("---")
    L.append("*Bibliographic data are facts and freely reusable; verify all "
             "generated synthesis text against the cited sources.*")

    Path(path).write_text("\n".join(L), encoding="utf-8")
    return Path(path)


# ── PRISMA flow export ────────────────────────────────────────────────────────

def export_prisma_markdown(path: Path) -> Path:
    c = audit.prisma_counts()
    L = [
        "# PRISMA 2020 Flow (auto-generated)",
        "",
        f"*Generated {time.strftime('%Y-%m-%d %H:%M')} from ResearchBuddy's "
        "audit trail.*",
        "",
        "## Identification",
        f"- Records identified via database searches: **{c['identified_search']}** "
        f"(across {c['n_searches']} searches)",
        f"- Records identified via citation snowballing: "
        f"**{c['identified_snowball']}**",
        f"- Records identified via living-review watches: "
        f"**{c['identified_watch']}**",
    ]
    if c["identified_by_source"]:
        L.append("- By source: " + ", ".join(
            f"{k}: {v}" for k, v in sorted(c["identified_by_source"].items())))
    L += [
        "",
        "## Screening",
        f"- Records screened (rated): **{c['screened']}**",
        f"- Included (rating ≥ {REVIEW_MIN_RATING_INCLUDE}): **{c['included']}**",
        f"- Excluded: **{c['excluded']}**",
        "",
        "## Full text",
        f"- Full texts retrieved from legal open-access sources: "
        f"**{c['fulltext_retrieved']}**",
        "",
        "*Counts reflect logged events; papers screened before the audit "
        "trail was enabled are not included.*",
    ]
    Path(path).write_text("\n".join(L), encoding="utf-8")
    return Path(path)


# ── Pack orchestrator ─────────────────────────────────────────────────────────

def export_review_pack(graph: HierarchicalResearchGraph,
                       out_dir: Optional[Path] = None,
                       use_llm: bool = True) -> Path:
    """Write all review deliverables into a timestamped pack directory."""
    stamp = time.strftime("%Y%m%d_%H%M%S")
    pack = Path(out_dir) if out_dir else REVIEW_EXPORT_DIR / f"pack_{stamp}"
    pack.mkdir(parents=True, exist_ok=True)

    papers = review_papers(graph)
    n_bib = export_bibtex(graph, pack / "review.bib", papers)
    export_ris(graph, pack / "review.ris", papers)
    export_synthesis_matrix(graph, pack / "synthesis_matrix.csv", papers)
    export_review_scaffold(graph, pack / "review_scaffold.md", papers,
                           use_llm=use_llm)
    export_prisma_markdown(pack / "prisma_flow.md")

    n_included = sum(1 for m in papers
                     if (m.user_rating or 0) >= REVIEW_MIN_RATING_INCLUDE)
    audit.log_event("export", pack_dir=str(pack),
                    n_papers=n_bib, n_included=n_included)
    return pack
